import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {ReactNode} from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}><CustomHeader children={children}/> </body>
    </html>
  )
}

const CustomHeader = ({
                    children,
                }: {
    children: React.ReactNode
}) => {
    return (
        <div>{children}</div>
    )
}
